//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfUI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MethodParameters {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MethodParameters() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfUI.Resources.MethodParameters", typeof(MethodParameters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha.
        /// </summary>
        public static string AntAlpha {
            get {
                return ResourceManager.GetString("AntAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beta.
        /// </summary>
        public static string AntBeta {
            get {
                return ResourceManager.GetString("AntBeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial pheromone.
        /// </summary>
        public static string AntInitialPheromone {
            get {
                return ResourceManager.GetString("AntInitialPheromone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interatins without improvements.
        /// </summary>
        public static string AntIterations {
            get {
                return ResourceManager.GetString("AntIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to p (pheromon evaporation speed).
        /// </summary>
        public static string AntP {
            get {
                return ResourceManager.GetString("AntP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q.
        /// </summary>
        public static string AntQ {
            get {
                return ResourceManager.GetString("AntQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterations without improvements.
        /// </summary>
        public static string GeneticIterations {
            get {
                return ResourceManager.GetString("GeneticIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mutation probability.
        /// </summary>
        public static string GeneticMutationProbability {
            get {
                return ResourceManager.GetString("GeneticMutationProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iterations.
        /// </summary>
        public static string RngIterations {
            get {
                return ResourceManager.GetString("RngIterations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial t.
        /// </summary>
        public static string SAInitialT {
            get {
                return ResourceManager.GetString("SAInitialT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T min.
        /// </summary>
        public static string SATmin {
            get {
                return ResourceManager.GetString("SATmin", resourceCulture);
            }
        }
    }
}
